services:
  mosquitto:
    image: eclipse-mosquitto:2
    restart: unless-stopped
    volumes:
      - ./mosquitto/conf:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
    networks: [iot]

  api:
    build: ./api            # tu Dockerfile con Uvicorn
    restart: unless-stopped
    environment:
      MQTT_HOST: mosquitto
      MQTT_PORT: 1883
      MQTT_TOPIC: factory/cmd
    depends_on: [mosquitto]
    ports:
      - "8000:8000"
    networks: [iot]

networks:
  iot:


