services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    restart: unless-stopped
    volumes:
      - ./mosquitto/conf:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
    networks: [iot]

  api:
    build: ./api       # tu código FastAPI
    container_name: fastapi
    restart: unless-stopped
    environment:
      - MQTT_HOST=mosquitto
      - MQTT_PORT=1883
    depends_on: [mosquitto]
    ports:
      - "8000:8000"
    networks: [iot]

networks:
  iot:

