version: '3.8'

services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    ports:
      - "1883:1883"
    volumes:
      - './mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf'
      - './mosquitto/data:/mosquitto/data'
      - './mosquitto/log:/mosquitto/log'
    restart: unless-stopped

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - mosquitto
    restart: unless-stopped

  chirpstack:
    image: chirpstack/chirpstack:4
    container_name: chirpstack
    ports:
      - "8080:8080"        # Interfaz web
      - "1700:1700/udp"    # Tráfico LoRaWAN
    volumes:
      - './chirpstack/config:/etc/chirpstack'
      - './chirpstack/data:/var/lib/chirpstack'
    environment:
      - CHIRPSTACK_API_PUBLIC_HOST=0.0.0.0
    depends_on:
      - mosquitto
    restart: unless-stopped

