services:
  mosquitto:
    image: eclipse-mosquitto:2.0.15
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    networks: [iot]

  fastapi:
    build: ./api
    container_name: fastapi
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    depends_on: [mosquitto]
    ports:
      - "8000:8000"
    networks: [iot]

  frontend:
    build: ./frontend
    container_name: lorafront
    restart: unless-stopped
    depends_on:
      - fastapi
    environment:
      - API_URL=http://fastapi:8000
    ports:
      - "5000:5000"
    networks: [iot]

networks:
  iot:
