# Archivo de configuración básico para The Things Stack
is:
  # Configuración del Identity Server
  database-uri: postgres://username:password@postgres:5432/ttn_lorawan
redis:
  # Configuración de Redis
  address: redis:6379
mqtt:
  # Configuración del broker MQTT integrado
  public-address: 'mosquitto:1883'
  public-tls-address: ''

