# ===========================
# ChirpStack Gateway Bridge
# ===========================

[general]
# Nivel de logs: trace, debug, info, warning, error
log_level = "info"

[integration]
# Definimos la integración con MQTT
[integration.mqtt]
event_topic = "gateway/+/event/+"
command_topic = "gateway/{gateway_id}/command/#"
server = "tcp://mqtt:1883"
username = ""
password = ""
# Si tu broker MQTT requiere usuario/contraseña, introdúcelos aquí
# e.g.: username = "user", password = "pass"

# --------------
# Backend: Semtech UDP
# --------------
[backend]
# Tipo de backend
type = "semtech_udp"

[backend.semtech_udp]
# El Bridge escuchará en UDP/1700 dentro del contenedor
# para recibir los paquetes del packet-forwarder
udp_bind = "0.0.0.0:1700"

# Omite verificación de CRC para gateways single-channel
skip_crc_check = true

# (Opcional) otras configuraciones de timings, timeouts, etc.
