name: SonarQube Scan

on:
  push:
    branches:
      - main
      - develop
      - test
  pull_request:
    branches:
      - main
      - develop
      - test
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Desactivar shallow clones mejora la detección de cambios para PR
          fetch-depth: 0

      - name: Set up Python (solo si tu proyecto usa Py)
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies (opcional)
        if: ${{ hashFiles('**/requirements.txt') != '' }}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v1
        env:
          SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }} # o secrets.SONAR_HOST_URL si prefieres secreto
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=${{ github.repository }}

      - name: Quality Gate
        uses: SonarSource/sonarqube-quality-gate-action@v1
        env:
          SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

